spring:
  profiles: dev
  application:1
    name: goat-config-fuck-dev

---

spring:
  profiles: test
  application:
    name: goat-config-fuck-test

---

spring:
  profiles: pro
  application:
    name: goat-config-fuck-pro